services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     - SQLALCHEMY_DATABASE_URL=${DATABASE_URL}
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - JWT_ALGORITHM=${JWT_ALGORITHM}
  #     - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
  #     - JWT_REFRESH_TOKEN_EXPIRE_DAYS=${JWT_REFRESH_TOKEN_EXPIRE_DAYS}
  #   depends_on:
  #     - mysql
  #   restart: always
  #   networks:
  #     - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - env.mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql 
      - mysql_conf:/etc/mysql/conf.d 
    restart: always
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_conf:

networks:
  app-network:
    driver: bridge